// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// K_S
Rcpp::NumericVector K_S(arma::mat mt, arma::mat mt2);
RcppExport SEXP _diffCompVarRcpp_K_S(SEXP mtSEXP, SEXP mt2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mt(mtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mt2(mt2SEXP);
    rcpp_result_gen = Rcpp::wrap(K_S(mt, mt2));
    return rcpp_result_gen;
END_RCPP
}
// column_median
Rcpp::NumericVector column_median(arma::mat x);
RcppExport SEXP _diffCompVarRcpp_column_median(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(column_median(x));
    return rcpp_result_gen;
END_RCPP
}
// column_mean
Rcpp::NumericVector column_mean(arma::mat x);
RcppExport SEXP _diffCompVarRcpp_column_mean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(column_mean(x));
    return rcpp_result_gen;
END_RCPP
}
// column_medianVar
Rcpp::NumericVector column_medianVar(arma::mat x, arma::mat m);
RcppExport SEXP _diffCompVarRcpp_column_medianVar(SEXP xSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(column_medianVar(x, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_diffCompVarRcpp_K_S", (DL_FUNC) &_diffCompVarRcpp_K_S, 2},
    {"_diffCompVarRcpp_column_median", (DL_FUNC) &_diffCompVarRcpp_column_median, 1},
    {"_diffCompVarRcpp_column_mean", (DL_FUNC) &_diffCompVarRcpp_column_mean, 1},
    {"_diffCompVarRcpp_column_medianVar", (DL_FUNC) &_diffCompVarRcpp_column_medianVar, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_diffCompVarRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
